### ISSUE TITLE
Fix the error when creating 2 tasks

### ISSUE THREAD

**Issue by zedtux** [Linc-Lu/rails-exercise#1]
When a user creates a first task, all is going well, but then if he set a new task title and submit the form there is an error `The action 'update' could not be found for TasksController`. We don't want to add this action.
Instead we would like to create a new task without any errors.

**Comment by ayoubben** [comment]
i don't get this error !! i can create two tasks with the same user.

**Comment by zedtux** [comment]
You're right @ayoubben, the bug is no more present since I have added the interactors. Thank you :)
